#!/usr/bin/env python3
"""
Claude-driven QA loop for the reproduction web app  (pipeline component 5).

The static site is generated by ``build_webapp.py`` into  <repo>/webapp/ .  This
harness closes the loop on its *quality*: it invokes the local ``claude`` CLI
headlessly to inspect the built site and return a structured pass/fail verdict,
and — when the verdict is *fail* — invokes a second, "developer" ``claude`` pass
to fix ``build_webapp.py`` / its inline templates, rebuilds the site, and
re-QAs.  It repeats until the site passes or an iteration budget is exhausted.

What the QA pass checks (read-only inspection of webapp/ + webapp/data/status.json):
  1. NEW paper sections  -- every paper added since the last passing QA run is
     actually present as its own ``papers/<id>.html`` page, correctly linked
     from ``index.html``, and wired into the dashboard search/filter data.
  2. Structure           -- index + per-paper pages exist, assets resolve,
     status.json is internally consistent with the rendered pages.
  3. Flow / design       -- tabs, cards, filters and the dark "scientific" theme
     render coherently; no obviously broken markup or dead links.
  4. Manim animations    -- papers flagged ``has_manim`` expose a working
     Animation tab whose <video>/<img> ``src`` points at a media file that
     exists on disk (the central interactive artefact of each reproduction).
  5. Usability           -- search box, area/status chips, tabs and the figure
     lightbox are present and their JS handlers are wired up.

Design notes / constraints honoured:
  * Windows, CPU-only, Python 3.10 in the project ``.venv``.  Nothing here needs
    a GPU; if a future check needs heavy compute it must scale down and record
    the deviation in the report rather than fail hard.
  * Every ``claude`` invocation is HEADLESS (``claude -p ... --dangerously-skip-
    permissions``) and BOUNDED by a wall-clock timeout; the whole child tree is
    killed on timeout.
  * ``config.json`` is READ-ONLY here (only the orchestrator edits it).
  * ``paper_pipeline.py`` is never touched; its API is preserved.
  * The GitHub token is NEVER read for logic here, and any value that might be a
    token is scrubbed from captured output before it is written to the report.
    Nothing is committed.

Usage:
    python qa_agent.py --config ../config.json
    python qa_agent.py --config ../config.json --max-iters 3 --qa-minutes 15 --dev-minutes 25
    python qa_agent.py --config ../config.json --new-ids DL-some-slug ML-other-slug
    python qa_agent.py --config ../config.json --no-fix          # report only, never invoke the developer pass
    python qa_agent.py --config ../config.json --run-tests       # rebuild with per-paper pytest badges
"""
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))
import pipeline_paths  # noqa: E402
from secrets_helper import get_secret  # noqa: E402

# --------------------------------------------------------------------------- #
# structured verdict contract
# --------------------------------------------------------------------------- #
# The QA claude pass writes a JSON object matching this shape to a file we hand
# it.  We normalise whatever comes back so the loop always has a usable verdict.
VERDICT_KEYS = ("verdict", "summary", "issues", "checks")
SEVERITIES = ("critical", "major", "minor", "nit")

# --------------------------------------------------------------------------- #
# prompts
# --------------------------------------------------------------------------- #
QA_PROMPT_TEMPLATE = """You are a meticulous QA reviewer for a STATIC research web app. Work autonomously; never ask questions. This is a READ-ONLY review: do NOT modify, build, serve, or delete any file — only inspect.

THE SITE (already built) lives at:
  {webapp_dir}
Key files to inspect:
  - index.html                the dashboard (stat cards, search box, area/status chips, paper cards)
  - papers/<id>.html          one tabbed page per paper (Overview / Paper PDF / Summary / Figures / Source / Tests / Animation / Data)
  - assets/style.css , assets/app.js   the shared theme + client-side tabs/filters/lightbox
  - data/status.json          machine-readable build summary the site was generated from

NEWLY ADDED papers that MUST be verified as correctly integrated this run:
{new_sections}

Build summary (data/status.json says):
{status_summary}

REVIEW CHECKLIST — inspect the actual HTML/CSS/JS/JSON and judge each:
  1. NEW SECTIONS: for every new paper id above, confirm papers/<id>.html exists, is a valid complete page, is linked from a card in index.html, and its card carries the right area code + search/filter data attributes. Flag any new paper that is missing, unlinked, or malformed.
  2. STRUCTURE: index.html and every per-paper page reference assets/style.css and assets/app.js with paths that resolve; the counts/flags in data/status.json (paper count, has_manim, reproduced_figs, tests, has_paper_pdf, has_summary_pdf) match what the pages actually render. Flag mismatches and dead relative links.
  3. FLOW / DESIGN: the dark scientific theme is coherent; the tab strip, cards grid, stat cells and pills are well-formed markup (no unclosed tags, no leftover @@PLACEHOLDER@@ tokens, no empty required regions). Flag broken or visually incoherent structure.
  4. MANIM ANIMATIONS (the central interactive artefact): every paper with has_manim=true in status.json must have an Animation tab whose <video><source src> or <img src> points at a media file (.mp4/.webm/.gif) that EXISTS on disk relative to the page. Missing media, empty Animation panels, or has_manim mismatches are MAJOR issues.
  5. USABILITY: the search input, the area chips (All/AI/DS/ML/DL), the status chips (Reproduced/Animated), the tab buttons and the figure lightbox all exist AND app.js wires up handlers for them. Flag any control that is present but non-functional, or wired but absent.

Be concrete: cite the exact file and what is wrong. Distinguish severities: "critical" (site broken/new paper missing), "major" (a checklist item fails), "minor"/"nit" (polish). Only "critical" or "major" issues should make the verdict fail; pure nits do not.

WHEN DONE, write your verdict as a SINGLE JSON object (and nothing else) to EXACTLY this file:
  {verdict_path}
Use this schema:
{{
  "verdict": "pass" | "fail",
  "summary": "<2-4 sentence overall assessment>",
  "checks": {{
    "new_sections": "pass" | "fail",
    "structure": "pass" | "fail",
    "flow_design": "pass" | "fail",
    "manim_animations": "pass" | "fail",
    "usability": "pass" | "fail"
  }},
  "issues": [
    {{"severity": "critical|major|minor|nit", "area": "<check name>", "file": "<path or ''>", "description": "<what is wrong>", "suggested_fix": "<how build_webapp.py or its templates should change>"}}
  ]
}}
Set "verdict":"pass" only if there are NO critical and NO major issues. Write the file even when everything passes (with an empty or nits-only "issues" list). Your final chat message must be one line: PASS or FAIL plus the issue count.
"""

DEV_PROMPT_TEMPLATE = """You are a developer fixing a STATIC web app generator. Work autonomously; never ask questions. Everything you change must keep the generator runnable.

The site is generated by:
  {build_script}
It emits the site into <repo>/webapp/ (index.html, papers/<id>.html, assets/style.css, assets/app.js, data/status.json). The CSS, JS and HTML templates are INLINE inside build_webapp.py (the CSS/JS/INDEX string constants) — fix them THERE, not by hand-editing generated files (generated files are overwritten on the next build).

A QA review of the built site FAILED. Fix the ROOT CAUSE of each issue below by editing {build_script} (and only, if strictly necessary, other files under <repo>/scripts/ or the site templates it writes). Then the harness will re-run the build and re-QA — you do NOT need to run the build yourself, but your changes must make it produce a correct site.

QA VERDICT SUMMARY:
{qa_summary}

ISSUES TO FIX (address every critical and major one):
{issue_list}

HARD RULES:
  - Do NOT modify config.json (only the orchestrator edits it).
  - Do NOT modify paper_pipeline.py — its public API must stay intact.
  - Do NOT touch anything under the repo's raw/ research folders or the per-paper AREA folders' source content; you are fixing the GENERATOR and its templates only.
  - Do NOT print, log, echo, or commit any secret/token. Do not run git commit/push.
  - Keep it dependency-free and CPU-only, consistent with the existing generator. Preserve the existing dark scientific theme and the data/status.json schema that the QA step reads.
  - Make minimal, targeted edits that fix the reported issues without regressing other pages.

When finished, stop. Your final message must be a 2-4 line summary of exactly which issues you fixed and where.
"""


# --------------------------------------------------------------------------- #
# config / io helpers
# --------------------------------------------------------------------------- #
def load_config(path: Path) -> dict[str, Any]:
    """Read config.json. READ-ONLY — this harness never writes it back."""
    return json.loads(path.read_text(encoding="utf-8"))


def read_json(path: Path) -> dict[str, Any] | None:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:  # noqa: BLE001
        return None


def write_json(path: Path, obj: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(obj, ensure_ascii=False, indent=2), encoding="utf-8")


# --------------------------------------------------------------------------- #
# token scrubbing — a secret must never reach the report or logs
# --------------------------------------------------------------------------- #
# optional PAT file (github.token_file in config / GITHUB_TOKEN_FILE env);
# main() re-resolves this once the config is loaded.
_TOKEN_FILE: Path | None = pipeline_paths.token_file()
_SECRET_PATTERNS = (
    re.compile(r"gh[pousr]_[A-Za-z0-9]{20,}"),
    re.compile(r"github_pat_[A-Za-z0-9_]{20,}"),
    re.compile(r"x-access-token:[^@\s]+@"),
)


def _secret_values() -> list[str]:
    """Collect concrete secret values to redact (never logged individually)."""
    vals: list[str] = []
    for key in ("GITHUB_TOKEN", "GITHUB_ACCESS_TOKEN", "GH_TOKEN"):
        v = os.environ.get(key)
        if v and len(v) >= 8:
            vals.append(v)
    try:
        # Resolve the real PAT (Secret Manager first, local token file as
        # fallback) purely so it can be redacted from captured output. The value
        # is only ever added to the redaction list; it is never logged.
        t = get_secret(
            "github-pat", env="GITHUB_TOKEN",
            file_fallback=str(_TOKEN_FILE) if _TOKEN_FILE else None,
        ).strip()
        if t and len(t) >= 8:
            vals.append(t)
    except Exception:  # noqa: BLE001
        pass
    return vals


def scrub(text: str) -> str:
    """Redact any concrete token value and token-shaped strings from text."""
    if not text:
        return text
    for v in _secret_values():
        text = text.replace(v, "[REDACTED]")
    for pat in _SECRET_PATTERNS:
        text = pat.sub("[REDACTED]", text)
    return text


def tail_file(path: Path, n: int = 60) -> str:
    try:
        lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    except Exception:  # noqa: BLE001
        return ""
    return scrub("\n".join(lines[-n:]))


# --------------------------------------------------------------------------- #
# headless claude runner (mirrors reproduce.run_claude)
# --------------------------------------------------------------------------- #
def run_claude(claude_exe: str, repo_root: Path, cwd: Path, prompt: str,
               minutes: int, logf: Path) -> tuple[str, int]:
    """Invoke claude headlessly in ``cwd`` with a hard timeout.

    Returns (status, returncode). The child's env is inherited (claude needs its
    own auth) but is NEVER written anywhere by us. On timeout the whole child
    tree is killed (claude spawns node children on Windows).
    """
    args = [claude_exe, "-p", prompt, "--dangerously-skip-permissions",
            "--add-dir", str(repo_root)]
    logf.parent.mkdir(parents=True, exist_ok=True)
    with logf.open("w", encoding="utf-8", errors="replace") as out:
        try:
            proc = subprocess.Popen(
                args, cwd=str(cwd), stdin=subprocess.DEVNULL,
                stdout=out, stderr=subprocess.STDOUT, text=True,
            )
        except FileNotFoundError:
            return ("claude-not-found", -1)
        try:
            proc.wait(timeout=minutes * 60)
            return ("completed", proc.returncode)
        except subprocess.TimeoutExpired:
            if os.name == "nt":
                # kill the whole tree (claude spawns node children on Windows)
                subprocess.run(["taskkill", "/F", "/T", "/PID", str(proc.pid)],
                               stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            else:
                proc.kill()
            return ("timeout", -2)


# A claude run that dies on a transient API/limit error leaves a short log with
# one of these signatures and never writes the verdict file.  Without retries
# the loop mislabels the outage as "QA pass produced no parseable verdict".
_TRANSIENT_ERROR_PATTERNS = (
    re.compile(r"API Error:\s*5\d\d", re.IGNORECASE),
    re.compile(r"\boverloaded\b", re.IGNORECASE),
    re.compile(r"session limit", re.IGNORECASE),
    re.compile(r"usage limit", re.IGNORECASE),
    re.compile(r"rate limit", re.IGNORECASE),
)
# a genuine QA/dev run produces far more output than an immediate API failure
_TRANSIENT_LOG_MAX_CHARS = 2000


def _transient_failure(logf: Path) -> str | None:
    """Return the error line if the log shows only a transient API failure."""
    try:
        text = logf.read_text(encoding="utf-8", errors="replace").strip()
    except Exception:  # noqa: BLE001
        return None
    if not text or len(text) > _TRANSIENT_LOG_MAX_CHARS:
        return None
    for pat in _TRANSIENT_ERROR_PATTERNS:
        if pat.search(text):
            return scrub(text.splitlines()[0])
    return None


def run_claude_with_retry(claude_exe: str, repo_root: Path, cwd: Path, prompt: str,
                          minutes: int, logf: Path, attempts: int = 3,
                          wait_s: int = 60) -> tuple[str, int]:
    """run_claude, retrying runs that die instantly on a transient API error.

    Returns run_claude's (status, returncode); if every attempt hits a
    transient error the status is "api-error" so callers can report the real
    outage instead of a generic missing-verdict failure.
    """
    code = -1
    for attempt in range(1, attempts + 1):
        status, code = run_claude(claude_exe, repo_root, cwd, prompt, minutes, logf)
        if status != "completed":
            return (status, code)
        err = _transient_failure(logf)
        if err is None:
            return (status, code)
        if attempt < attempts:
            print(f"[qa] claude run hit a transient error ({err}); "
                  f"retrying in {wait_s}s ({attempt}/{attempts - 1} retries used)")
            time.sleep(wait_s)
    return ("api-error", code)


# --------------------------------------------------------------------------- #
# build runner
# --------------------------------------------------------------------------- #
def run_build(python_exe: str, build_script: Path, repo_root: Path,
              run_tests: bool, logf: Path) -> tuple[bool, str]:
    """Regenerate the static site via build_webapp.py. Returns (ok, tail)."""
    args = [python_exe, str(build_script), "--repo", str(repo_root)]
    if run_tests:
        args += ["--run-tests", "--python", python_exe]
    logf.parent.mkdir(parents=True, exist_ok=True)
    try:
        proc = subprocess.run(args, cwd=str(build_script.parent),
                              capture_output=True, text=True, timeout=1800)
    except FileNotFoundError:
        logf.write_text("build_webapp.py or python interpreter not found",
                        encoding="utf-8")
        return (False, "build interpreter/script not found")
    except subprocess.TimeoutExpired:
        logf.write_text("build timed out (>1800s)", encoding="utf-8")
        return (False, "build timed out (>1800s)")
    out = scrub((proc.stdout or "") + (proc.stderr or ""))
    logf.write_text(out, encoding="utf-8")
    ok = proc.returncode == 0
    tail = "\n".join(out.splitlines()[-40:])
    return (ok, tail)


# --------------------------------------------------------------------------- #
# new-section discovery
# --------------------------------------------------------------------------- #
def load_status(webapp: Path) -> dict[str, Any] | None:
    return read_json(webapp / "data" / "status.json")


def paper_ids(status: dict[str, Any] | None) -> list[str]:
    if not status:
        return []
    return [p.get("id", "") for p in status.get("papers", []) if p.get("id")]


def compute_new_ids(status: dict[str, Any] | None, snapshot: dict[str, Any] | None,
                    override: list[str] | None) -> list[str]:
    """New paper ids = explicit override, else those absent from the snapshot."""
    if override:
        return sorted(set(override))
    current = set(paper_ids(status))
    if snapshot is None:
        # first ever QA run: treat every paper as "new" so all are verified.
        return sorted(current)
    seen = set(paper_ids(snapshot))
    return sorted(current - seen)


def format_new_sections(new_ids: list[str], status: dict[str, Any] | None) -> str:
    if not new_ids:
        return "  (none detected as new — verify the site as a whole instead.)"
    by_id = {p.get("id"): p for p in (status or {}).get("papers", [])}
    lines: list[str] = []
    for pid in new_ids:
        p = by_id.get(pid, {})
        extra = []
        if p:
            extra.append(f"area={p.get('code', '?')}")
            extra.append(f"has_manim={bool(p.get('has_manim'))}")
            extra.append(f"reproduced_figs={p.get('reproduced_figs', 0)}")
            title = str(p.get("title", ""))[:70]
            head = f"  - {pid}  ({', '.join(extra)})"
            if title:
                head += f"  — {title}"
            lines.append(head)
        else:
            lines.append(f"  - {pid}")
    return "\n".join(lines)


def format_status_summary(status: dict[str, Any] | None) -> str:
    if not status:
        return "  (data/status.json missing or unreadable — this is itself a defect.)"
    return (f"  total={status.get('total')}  reproduced={status.get('reproduced')}  "
            f"animated={status.get('animated')}  tests_passing={status.get('tests_passing')}  "
            f"by_area={status.get('by_area')}  generated={status.get('generated')}")


# --------------------------------------------------------------------------- #
# verdict handling
# --------------------------------------------------------------------------- #
def _extract_json_object(text: str) -> dict[str, Any] | None:
    """Best-effort: pull the first balanced {...} JSON object out of text."""
    start = text.find("{")
    while start != -1:
        depth = 0
        for i in range(start, len(text)):
            c = text[i]
            if c == "{":
                depth += 1
            elif c == "}":
                depth -= 1
                if depth == 0:
                    chunk = text[start:i + 1]
                    try:
                        obj = json.loads(chunk)
                        if isinstance(obj, dict):
                            return obj
                    except Exception:  # noqa: BLE001
                        break
        start = text.find("{", start + 1)
    return None


def read_verdict(verdict_path: Path, log_path: Path) -> tuple[dict[str, Any] | None, str]:
    """Load the verdict JSON claude was asked to write; fall back to its log."""
    raw = read_json(verdict_path)
    if isinstance(raw, dict):
        return raw, "verdict-file"
    # fall back: try to recover a JSON object from the run log
    try:
        log_text = log_path.read_text(encoding="utf-8", errors="replace")
    except Exception:  # noqa: BLE001
        log_text = ""
    recovered = _extract_json_object(log_text)
    if recovered:
        return recovered, "recovered-from-log"
    return None, "missing"


def normalize_verdict(raw: dict[str, Any] | None) -> dict[str, Any]:
    """Coerce whatever came back into a stable verdict dict with a 'passed' bool."""
    v: dict[str, Any] = {"verdict": "fail", "summary": "", "checks": {}, "issues": []}
    if isinstance(raw, dict):
        vv = str(raw.get("verdict", "")).strip().lower()
        v["verdict"] = "pass" if vv == "pass" else "fail"
        v["summary"] = str(raw.get("summary", ""))
        if isinstance(raw.get("checks"), dict):
            v["checks"] = raw["checks"]
        issues = raw.get("issues")
        if isinstance(issues, list):
            norm_issues = []
            for it in issues:
                if isinstance(it, dict):
                    sev = str(it.get("severity", "major")).strip().lower()
                    if sev not in SEVERITIES:
                        sev = "major"
                    norm_issues.append({
                        "severity": sev,
                        "area": str(it.get("area", "")),
                        "file": str(it.get("file", "")),
                        "description": scrub(str(it.get("description", ""))),
                        "suggested_fix": scrub(str(it.get("suggested_fix", ""))),
                    })
                else:
                    norm_issues.append({"severity": "major", "area": "",
                                        "file": "", "description": scrub(str(it)),
                                        "suggested_fix": ""})
            v["issues"] = norm_issues
    # a verdict is a genuine PASS only if it says pass AND has no blocking issues
    blocking = [i for i in v["issues"] if i["severity"] in ("critical", "major")]
    v["blocking_count"] = len(blocking)
    v["passed"] = (v["verdict"] == "pass" and len(blocking) == 0)
    return v


def fail_verdict(reason: str) -> dict[str, Any]:
    """Synthesise a failing verdict when the QA pass itself did not deliver one."""
    return normalize_verdict({
        "verdict": "fail",
        "summary": reason,
        "checks": {},
        "issues": [{"severity": "critical", "area": "qa-harness",
                    "file": "", "description": reason,
                    "suggested_fix": "Re-run QA; ensure the claude CLI is reachable "
                                     "and the webapp was built."}],
    })


# --------------------------------------------------------------------------- #
# QA + developer passes
# --------------------------------------------------------------------------- #
def qa_pass(claude_exe: str, repo_root: Path, webapp: Path, new_ids: list[str],
            status: dict[str, Any] | None, qa_dir: Path, minutes: int,
            stamp: str, itno: int) -> dict[str, Any]:
    verdict_path = qa_dir / f"verdict_{stamp}_iter{itno}.json"
    logf = qa_dir / f"qa_{stamp}_iter{itno}.log"
    # ensure a stale verdict from a previous iteration is not misread
    if verdict_path.exists():
        try:
            verdict_path.unlink()
        except Exception:  # noqa: BLE001
            pass
    prompt = QA_PROMPT_TEMPLATE.format(
        webapp_dir=str(webapp),
        new_sections=format_new_sections(new_ids, status),
        status_summary=format_status_summary(status),
        verdict_path=str(verdict_path),
    )
    run_status, code = run_claude_with_retry(claude_exe, repo_root, repo_root,
                                             prompt, minutes, logf)
    if run_status == "claude-not-found":
        v = fail_verdict("claude CLI not found — cannot run QA.")
    elif run_status == "timeout":
        raw, src = read_verdict(verdict_path, logf)
        v = normalize_verdict(raw) if raw else fail_verdict(
            f"QA pass timed out after {minutes}m and left no verdict.")
    elif run_status == "api-error":
        v = fail_verdict(
            "QA claude run failed on a transient API/limit error after retries: "
            f"{_transient_failure(logf) or '(see log)'}")
    else:
        raw, src = read_verdict(verdict_path, logf)
        v = normalize_verdict(raw) if raw is not None else fail_verdict(
            "QA pass produced no parseable verdict. "
            f"Last claude output: {tail_file(logf, 3) or '(empty log)'}")
    v["_run"] = {"status": run_status, "code": code, "log": str(logf),
                 "verdict_file": str(verdict_path)}
    return v


def dev_pass(claude_exe: str, repo_root: Path, build_script: Path,
             verdict: dict[str, Any], qa_dir: Path, minutes: int,
             stamp: str, itno: int) -> dict[str, Any]:
    logf = qa_dir / f"dev_{stamp}_iter{itno}.log"
    issues = [i for i in verdict.get("issues", [])
              if i["severity"] in ("critical", "major")] or verdict.get("issues", [])
    issue_list = "\n".join(
        f"  - [{i['severity']}] ({i['area']}) {i['file']}: {i['description']}"
        + (f"\n      suggested fix: {i['suggested_fix']}" if i.get("suggested_fix") else "")
        for i in issues) or "  (no explicit issues listed; improve overall correctness)"
    prompt = DEV_PROMPT_TEMPLATE.format(
        build_script=str(build_script),
        qa_summary=verdict.get("summary", "") or "(no summary)",
        issue_list=issue_list,
    )
    run_status, code = run_claude_with_retry(claude_exe, repo_root, repo_root,
                                             prompt, minutes, logf)
    return {"status": run_status, "code": code, "log": str(logf),
            "issues_targeted": len(issues)}


# --------------------------------------------------------------------------- #
# report writing
# --------------------------------------------------------------------------- #
def write_report(qa_dir: Path, stamp: str, report: dict[str, Any]) -> tuple[Path, Path]:
    json_path = qa_dir / f"qa_report_{stamp}.json"
    md_path = qa_dir / f"qa_report_{stamp}.md"
    write_json(json_path, report)

    lines: list[str] = []
    lines.append(f"# Web app QA report — {stamp}")
    lines.append("")
    final = "PASS ✅" if report["passed"] else "FAIL ❌"
    lines.append(f"**Final verdict:** {final}   "
                 f"(after {report['iterations_run']} / {report['max_iters']} iteration(s))")
    lines.append("")
    lines.append(f"- webapp: `{report['webapp']}`")
    lines.append(f"- new paper sections verified: "
                 f"{', '.join(report['new_ids']) if report['new_ids'] else '(none / whole-site)'}")
    lines.append(f"- fix loop enabled: {report['fix_enabled']}")
    lines.append("")
    for it in report["iterations"]:
        n = it["iteration"]
        v = it["verdict"]
        lines.append(f"## Iteration {n} — {'PASS' if v['passed'] else 'FAIL'}")
        if not it.get("build_ok", True):
            lines.append(f"- build: FAILED — {it.get('build_tail', '')}")
        else:
            lines.append("- build: ok")
        lines.append(f"- QA run: {v.get('_run', {}).get('status')} "
                     f"(log `{v.get('_run', {}).get('log')}`)")
        if v.get("summary"):
            lines.append(f"- summary: {v['summary']}")
        if v.get("checks"):
            chk = ", ".join(f"{k}={val}" for k, val in v["checks"].items())
            lines.append(f"- checks: {chk}")
        if v.get("issues"):
            lines.append(f"- issues ({v.get('blocking_count', 0)} blocking):")
            for i in v["issues"]:
                lines.append(f"    - **[{i['severity']}]** ({i['area']}) "
                             f"`{i['file']}` — {i['description']}")
        else:
            lines.append("- issues: none")
        if it.get("dev"):
            d = it["dev"]
            lines.append(f"- developer pass: {d['status']} "
                         f"(targeted {d['issues_targeted']} issue(s), log `{d['log']}`)")
        lines.append("")
    md_path.write_text(scrub("\n".join(lines)), encoding="utf-8")
    return json_path, md_path


# --------------------------------------------------------------------------- #
# main
# --------------------------------------------------------------------------- #
def main() -> int:
    here = Path(__file__).resolve().parent
    ap = argparse.ArgumentParser(
        description="Claude-driven QA loop for the reproduction web app (component 5).")
    ap.add_argument("--config", type=Path, default=here.parent / "config.json")
    ap.add_argument("--max-iters", type=int, default=3,
                    help="max QA->fix->rebuild cycles before giving up (default 3)")
    ap.add_argument("--qa-minutes", type=int, default=15,
                    help="wall-clock budget for each QA claude pass (default 15)")
    ap.add_argument("--dev-minutes", type=int, default=25,
                    help="wall-clock budget for each developer claude pass (default 25)")
    ap.add_argument("--new-ids", nargs="*", default=None,
                    help="explicit new paper ids (e.g. DL-slug) to verify; "
                         "default: diff against the last QA snapshot")
    ap.add_argument("--no-fix", action="store_true",
                    help="report only; never invoke the developer pass")
    ap.add_argument("--no-initial-build", action="store_true",
                    help="do not rebuild the site before the first QA pass")
    ap.add_argument("--run-tests", action="store_true",
                    help="rebuild with per-paper pytest badges (slower)")
    args = ap.parse_args()

    if not args.config.exists():
        print(f"[fatal] config not found: {args.config}")
        return 2
    cfg = load_config(args.config)  # READ-ONLY

    global _TOKEN_FILE
    _TOKEN_FILE = pipeline_paths.token_file(cfg)

    repo_root = pipeline_paths.repo_root(cfg)
    python_exe = pipeline_paths.python_exe(cfg)
    claude_exe = pipeline_paths.claude_exe(cfg)
    webapp = repo_root / "webapp"
    build_script = here / "build_webapp.py"
    qa_dir = repo_root / "state" / "qa"
    qa_dir.mkdir(parents=True, exist_ok=True)
    snapshot_path = qa_dir / "status_snapshot.json"

    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    print(f"[qa] webapp={webapp}")
    print(f"[qa] max_iters={args.max_iters} qa_minutes={args.qa_minutes} "
          f"dev_minutes={args.dev_minutes} fix={'off' if args.no_fix else 'on'}")

    # optional initial build so the site reflects the latest reproductions
    if not args.no_initial_build:
        ok, tail = run_build(python_exe, build_script, repo_root, args.run_tests,
                             qa_dir / f"build_{stamp}_iter0.log")
        print(f"[qa] initial build: {'ok' if ok else 'FAILED'}")
        if not ok:
            print(f"[qa] build tail: {tail}")

    snapshot = read_json(snapshot_path)
    status = load_status(webapp)
    new_ids = compute_new_ids(status, snapshot, args.new_ids)
    print(f"[qa] {len(new_ids)} new paper section(s) to verify: "
          f"{', '.join(new_ids) if new_ids else '(none / whole-site)'}")

    report: dict[str, Any] = {
        "stamp": stamp,
        "webapp": str(webapp),
        "repo_root": str(repo_root),
        "new_ids": new_ids,
        "max_iters": args.max_iters,
        "fix_enabled": not args.no_fix,
        "iterations": [],
        "iterations_run": 0,
        "passed": False,
    }

    passed = False
    for itno in range(1, args.max_iters + 1):
        print(f"\n[qa] === iteration {itno}/{args.max_iters} ===")
        status = load_status(webapp)  # refresh after any rebuild
        build_ok, build_tail = True, ""
        if itno > 1:
            # a fresh build already ran at the end of the previous iteration;
            # nothing to do here.
            pass

        verdict = qa_pass(claude_exe, repo_root, webapp, new_ids, status,
                          qa_dir, args.qa_minutes, stamp, itno)
        it_entry: dict[str, Any] = {
            "iteration": itno, "verdict": verdict,
            "build_ok": build_ok, "build_tail": build_tail,
        }
        print(f"[qa] verdict: {'PASS' if verdict['passed'] else 'FAIL'} "
              f"({verdict.get('blocking_count', 0)} blocking issue(s), "
              f"run={verdict.get('_run', {}).get('status')})")

        if verdict["passed"]:
            report["iterations"].append(it_entry)
            report["iterations_run"] = itno
            passed = True
            break

        # not passing: either stop (report-only) or run the developer + rebuild
        if args.no_fix or itno == args.max_iters:
            report["iterations"].append(it_entry)
            report["iterations_run"] = itno
            break

        # a qa-harness-only failure (claude outage / limits) has nothing for the
        # developer pass to fix in the generator — just re-QA next iteration.
        blocking = [i for i in verdict.get("issues", [])
                    if i["severity"] in ("critical", "major")]
        if blocking and all(i.get("area") == "qa-harness" for i in blocking):
            print("[qa] failure is qa-harness only (claude unavailable); "
                  "skipping developer pass and retrying QA")
            report["iterations"].append(it_entry)
            report["iterations_run"] = itno
            continue

        print(f"[qa] invoking developer pass to fix {verdict.get('blocking_count', 0)} "
              f"blocking issue(s)...")
        dev = dev_pass(claude_exe, repo_root, build_script, verdict, qa_dir,
                       args.dev_minutes, stamp, itno)
        it_entry["dev"] = dev
        print(f"[qa] developer pass: {dev['status']}")

        # rebuild the site with the developer's fixes, ready for the next QA loop
        b_ok, b_tail = run_build(python_exe, build_script, repo_root, args.run_tests,
                                 qa_dir / f"build_{stamp}_iter{itno}.log")
        it_entry["rebuild_ok"] = b_ok
        it_entry["rebuild_tail"] = b_tail
        print(f"[qa] rebuild after fix: {'ok' if b_ok else 'FAILED'}")

        report["iterations"].append(it_entry)
        report["iterations_run"] = itno

    report["passed"] = passed

    # on a clean pass, advance the snapshot so subsequent runs only re-verify
    # genuinely new papers.
    if passed:
        final_status = load_status(webapp)
        if final_status is not None:
            write_json(snapshot_path, final_status)

    json_path, md_path = write_report(qa_dir, stamp, report)
    print(f"\n[qa] {'PASS' if passed else 'FAIL'} after {report['iterations_run']} "
          f"iteration(s)")
    print(f"[qa] report: {json_path}")
    print(f"[qa] report: {md_path}")
    # exit 0 on pass, 1 on fail (so the daily pipeline can gate on it)
    return 0 if passed else 1


if __name__ == "__main__":
    sys.exit(main())
